project_id = "gyiycegbniblicrbikji"

[functions.update-forex-prices]
verify_jwt = false

[functions.fetch-ohlcv]
verify_jwt = false

[functions.calculate-indicators]
verify_jwt = false

[functions.analyze-forex-ai]
verify_jwt = false

[functions.stripe-webhook]
verify_jwt = false