// AUTO-GENERATED by @lovable.dev/mcp-js — do not edit. Regenerated by the Vite plugin.
// To take ownership, delete this banner line; the plugin then leaves the file alone.
// supabase function: mcp
// Bundled from src/lib/mcp/index.ts by @lovable.dev/mcp-js.
// src/lib/mcp/index.ts
import { auth, defineMcp } from "npm:@lovable.dev/mcp-js@0.24.0";

// src/lib/mcp/tools/get-latest-price.ts
import { createClient } from "npm:@supabase/supabase-js@^2.75.0";
import { defineTool } from "npm:@lovable.dev/mcp-js@0.24.0";
import { z } from "npm:zod@^3.25.76";
var SYMBOLS = ["EUR/USD", "GBP/USD", "USD/JPY", "USD/CHF", "AUD/USD", "NZD/USD", "USD/CAD"];
function sb(ctx) {
  return createClient(process.env.SUPABASE_URL, process.env.SUPABASE_PUBLISHABLE_KEY, {
    global: { headers: { Authorization: `Bearer ${ctx.getToken()}` } },
    auth: { persistSession: false, autoRefreshToken: false }
  });
}
var get_latest_price_default = defineTool({
  name: "get_latest_price",
  title: "Get latest forex price",
  description: "Returns the most recent price, bid, ask and spread for a supported forex pair.",
  inputSchema: {
    symbol: z.enum(SYMBOLS).describe("Forex pair symbol, e.g. EUR/USD")
  },
  annotations: { readOnlyHint: true, idempotentHint: true, openWorldHint: false },
  handler: async ({ symbol }, ctx) => {
    if (!ctx.isAuthenticated()) {
      return { content: [{ type: "text", text: "Not authenticated" }], isError: true };
    }
    const { data, error } = await sb(ctx).rpc("get_latest_forex_price", { p_symbol: symbol });
    if (error) return { content: [{ type: "text", text: error.message }], isError: true };
    const row = data?.[0];
    if (!row) return { content: [{ type: "text", text: `No price for ${symbol}` }] };
    return {
      content: [{ type: "text", text: JSON.stringify(row) }],
      structuredContent: { price: row }
    };
  }
});

// src/lib/mcp/tools/list-daily-forecasts.ts
import { createClient as createClient2 } from "npm:@supabase/supabase-js@^2.75.0";
import { defineTool as defineTool2 } from "npm:@lovable.dev/mcp-js@0.24.0";
import { z as z2 } from "npm:zod@^3.25.76";
function sb2(ctx) {
  return createClient2(process.env.SUPABASE_URL, process.env.SUPABASE_PUBLISHABLE_KEY, {
    global: { headers: { Authorization: `Bearer ${ctx.getToken()}` } },
    auth: { persistSession: false, autoRefreshToken: false }
  });
}
var list_daily_forecasts_default = defineTool2({
  name: "list_daily_forecasts",
  title: "List daily forecasts",
  description: "Latest statistical daily forecasts across all tracked forex pairs (direction, entry, SL, TP, probability).",
  inputSchema: {
    limit: z2.number().int().positive().describe("Max rows to return (1..50)").default(10)
  },
  annotations: { readOnlyHint: true, openWorldHint: false },
  handler: async ({ limit }, ctx) => {
    if (!ctx.isAuthenticated()) {
      return { content: [{ type: "text", text: "Not authenticated" }], isError: true };
    }
    const capped = Math.min(Math.max(limit ?? 10, 1), 50);
    const { data, error } = await sb2(ctx).from("daily_forecasts").select("*").order("created_at", { ascending: false }).limit(capped);
    if (error) return { content: [{ type: "text", text: error.message }], isError: true };
    return {
      content: [{ type: "text", text: JSON.stringify(data) }],
      structuredContent: { forecasts: data ?? [] }
    };
  }
});

// src/lib/mcp/tools/get-market-review.ts
import { createClient as createClient3 } from "npm:@supabase/supabase-js@^2.75.0";
import { defineTool as defineTool3 } from "npm:@lovable.dev/mcp-js@0.24.0";
function sb3(ctx) {
  return createClient3(process.env.SUPABASE_URL, process.env.SUPABASE_PUBLISHABLE_KEY, {
    global: { headers: { Authorization: `Bearer ${ctx.getToken()}` } },
    auth: { persistSession: false, autoRefreshToken: false }
  });
}
var get_market_review_default = defineTool3({
  name: "get_market_review",
  title: "Get latest market review",
  description: "Returns the most recent Bull/Bear + Master AI market review with top-ideas and context.",
  inputSchema: {},
  annotations: { readOnlyHint: true, openWorldHint: false },
  handler: async (_input, ctx) => {
    if (!ctx.isAuthenticated()) {
      return { content: [{ type: "text", text: "Not authenticated" }], isError: true };
    }
    const { data, error } = await sb3(ctx).from("daily_market_reviews").select("id, session, market_context, created_at").order("created_at", { ascending: false }).limit(1).maybeSingle();
    if (error) return { content: [{ type: "text", text: error.message }], isError: true };
    if (!data) return { content: [{ type: "text", text: "No market review available yet." }] };
    return {
      content: [{ type: "text", text: data.market_context }],
      structuredContent: { review: data }
    };
  }
});

// src/lib/mcp/tools/get-my-credits.ts
import { createClient as createClient4 } from "npm:@supabase/supabase-js@^2.75.0";
import { defineTool as defineTool4 } from "npm:@lovable.dev/mcp-js@0.24.0";
function sb4(ctx) {
  return createClient4(process.env.SUPABASE_URL, process.env.SUPABASE_PUBLISHABLE_KEY, {
    global: { headers: { Authorization: `Bearer ${ctx.getToken()}` } },
    auth: { persistSession: false, autoRefreshToken: false }
  });
}
var get_my_credits_default = defineTool4({
  name: "get_my_credits",
  title: "Get my credits balance",
  description: "Returns the signed-in user's remaining AI analysis credits.",
  inputSchema: {},
  annotations: { readOnlyHint: true, openWorldHint: false },
  handler: async (_input, ctx) => {
    if (!ctx.isAuthenticated()) {
      return { content: [{ type: "text", text: "Not authenticated" }], isError: true };
    }
    const { data, error } = await sb4(ctx).from("user_credits").select("credits_balance").eq("user_id", ctx.getUserId()).maybeSingle();
    if (error) return { content: [{ type: "text", text: error.message }], isError: true };
    const balance = data?.credits_balance ?? 0;
    return {
      content: [{ type: "text", text: `You have ${balance} credits.` }],
      structuredContent: { credits_balance: balance }
    };
  }
});

// src/lib/mcp/tools/list-my-demo-trades.ts
import { createClient as createClient5 } from "npm:@supabase/supabase-js@^2.75.0";
import { defineTool as defineTool5 } from "npm:@lovable.dev/mcp-js@0.24.0";
import { z as z3 } from "npm:zod@^3.25.76";
function sb5(ctx) {
  return createClient5(process.env.SUPABASE_URL, process.env.SUPABASE_PUBLISHABLE_KEY, {
    global: { headers: { Authorization: `Bearer ${ctx.getToken()}` } },
    auth: { persistSession: false, autoRefreshToken: false }
  });
}
var list_my_demo_trades_default = defineTool5({
  name: "list_my_demo_trades",
  title: "List my demo trades",
  description: "Returns the signed-in user's demo trades (open and closed), most recent first.",
  inputSchema: {
    status: z3.enum(["OPEN", "CLOSED", "ALL"]).describe("Filter by status").default("ALL")
  },
  annotations: { readOnlyHint: true, openWorldHint: false },
  handler: async ({ status }, ctx) => {
    if (!ctx.isAuthenticated()) {
      return { content: [{ type: "text", text: "Not authenticated" }], isError: true };
    }
    let q = sb5(ctx).from("demo_trades").select("*").eq("user_id", ctx.getUserId()).order("opened_at", { ascending: false }).limit(50);
    if (status && status !== "ALL") q = q.eq("status", status);
    const { data, error } = await q;
    if (error) return { content: [{ type: "text", text: error.message }], isError: true };
    return {
      content: [{ type: "text", text: JSON.stringify(data) }],
      structuredContent: { trades: data ?? [] }
    };
  }
});

// src/lib/mcp/index.ts
var projectRef = "gyiycegbniblicrbikji";
var mcp_default = defineMcp({
  name: "fx-signal-suite-mcp",
  title: "FX Signal Suite",
  version: "0.1.0",
  instructions: "Tools for FX Signal Suite: read latest forex prices, statistical daily forecasts, the current AI market review, your credit balance, and your demo trading account. All calls run as the signed-in user.",
  auth: auth.oauth.issuer({
    issuer: `https://${projectRef}.supabase.co/auth/v1`,
    acceptedAudiences: "authenticated"
  }),
  tools: [
    get_latest_price_default,
    list_daily_forecasts_default,
    get_market_review_default,
    get_my_credits_default,
    list_my_demo_trades_default
  ]
});

// lovable-mcp-supabase-entry.ts
import { createSupabaseHandler } from "npm:@lovable.dev/mcp-js@0.24.0/stacks/supabase";
Deno.serve(createSupabaseHandler(mcp_default, { functionName: "mcp" }));
